motors:
  debris:
    dir:  GPIO23
    step: GPIO24
    encoder_a: GPIO25
    encoder_b: GPIO8
    encoder_z: GPIO7
  reel:
    step: GPIO17
    dir:  GPIO27
    encoder_a: GPIO22
    encoder_b: GPIO10
    encoder_z: GPIO9
  tensioning:
    step: GPIO5
    dir:  GPIO6
    encoder_a: GPIO13
    encoder_b: GPIO19
    encoder_z: GPIO26
servos:
  lid:
    pwm: GPIO21
