motors:
  debris:
    dir:    2
    step:   3
    enable: 4
    encoder_a: 17
    encoder_b: 27
    encoder_z: 22
  reel:
    dir:    10
    step:   9
    enable: 11
    encoder_a: 5
    encoder_b: 6
    encoder_z: 13
  tensioning:
    dir:    14
    step:   15
    enable: 18
    encoder_a: 23
    encoder_b: 24
    encoder_z: 25
servos:
  lid:
    pwm: 21
